### ISSUE TITLE
Minor fix

### ISSUE THREAD

**Issue by Sheshank-s** [csf30816/csf30816.github.io#1]
Thanks for adding me too your friends <3

Anyways, you have my site as "greenbayrules.com" It is actually, "greenbayrules.github.io" Just wanted you to fix that :D 

Packers

**Comment by ateesdalejr** [comment]
@GreenBayRules This is what pull requests are for. 📦

**Comment by Sheshank-s** [comment]
im lazy :P

________________________________

**Comment by csf30816** [comment]
OK i'll merge redmangos, sorry bout that
